#!/usr/bin/env php
<?php

require_once __DIR__ . '/vendor/autoload.php';

use Mdtt\RunCommand;
use Symfony\Component\Console\Application;

$app = new Application('MDTT', 'v1.0.0');
$app->add(new RunCommand());
$app->run();
