#!/usr/bin/env php
<?php

require_once __DIR__ . '/vendor/autoload.php';

use Mdtt\AppKernel;
use Mdtt\Application;

// TODO: Replace by env variable.
$kernel = new AppKernel("dev", false);
$kernel->boot();

$container = $kernel->getContainer();
$app = $container->get(Application::class);
$app->run();
