#!/usr/bin/env php
<?php

use Mdtt\Application;
use Symfony\Component\Config\FileLocator;
use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\DependencyInjection\Loader\YamlFileLoader;

/**
 * Determine vendor directory.
 */
$vendorDirectory = '';

if (file_exists(__DIR__.'/vendor/autoload.php')) {
    $vendorDirectory = __DIR__.'/vendor';
}

if (empty($vendorDirectory)) {
    throw new \RuntimeException('Unable to find vendor directory');
}

require $vendorDirectory . '/autoload.php';

$container = new ContainerBuilder();

$container->setParameter('vendor_directory', $vendorDirectory);

$loader    = new YamlFileLoader($container, new FileLocator());
$loader->load(__DIR__.'/config/services.yml');

$container->compile();

($container->get(Application::class))->run();
