services:
  _defaults:
    autowire: true
  _instanceof:
    Symfony\Component\Console\Command\Command:
      tags: [ 'app.command' ]

  # Contributed services.
  Monolog\Logger:
    class: \Monolog\Logger
    arguments:
      # Log channel name.
      - 'mdtt'

  # Custom services.
  logger:
    class: \Mdtt\Logger\DefaultLogger
    arguments:
      - '@Monolog\Logger'

  Psr\Log\LoggerInterface: '@logger'

  transform_plugin_manager:
    class: \Mdtt\Transform\DefaultPluginManager

  Mdtt\Transform\PluginManager: '@transform_plugin_manager'

  load_definition:
    class: \Mdtt\LoadDefinition\DefaultLoader

  Mdtt\LoadDefinition\Load: '@load_definition'

  Mdtt\:
    lazy: true
    resource: '../src/*'

  Mdtt\Application:
    public: true
    arguments:
      - !tagged_iterator app.command
