services:
  _defaults:
    autowire: true
    autoconfigure: true

  Mdtt\:
    resource: '../src'
    exclude:
        - '../src/DependencyInjection/'
        - '../src/AppKernel.php'

  logger:
    class: Symfony\Component\HttpKernel\Log\Logger
    autowire: false

  Psr\Log\LoggerInterface: '@logger'

  Mdtt\Application:
    public: true
