services:
  _defaults:
    autowire: true
  _instanceof:
    Symfony\Component\Console\Command\Command:
      tags: [ 'app.command' ]

  Symfony\Component\Mailer\:
    resource: '%vendor_directory%/symfony/mailer'

  Symfony\Component\Mailer\Transport\TransportInterface:
    class: \Symfony\Component\Mailer\Transport\SendmailTransport

  Psr\Log\:
    resource: '%vendor_directory%/psr/log/src'

  Mdtt\:
    lazy: true
    resource: '../src/*'

  Mdtt\Application:
    public: true
    arguments:
      - !tagged_iterator app.command
